# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.CharField(max_length=100)),
                ('editado_por', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(default='cliente_default.png', upload_to='', verbose_name='Foto')),
                ('pessoa_juridica', models.BooleanField(default=True, verbose_name='Pessoa Jurídica')),
                ('nome_fantasia', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('razao_social', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Razão Social')),
                ('cnpj', models.CharField(blank=True, max_length=50, null=True, verbose_name='CNPJ')),
                ('cpf', models.CharField(blank=True, max_length=50, null=True, verbose_name='CPF')),
                ('rua_endereco', models.CharField(blank=True, max_length=200, null=True, verbose_name='Rua')),
                ('numero_endereco', models.CharField(blank=True, max_length=10, null=True, verbose_name='Rua')),
                ('complemento_endereco', models.CharField(blank=True, max_length=10, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cidade')),
                ('cep', models.IntegerField(blank=True, null=True, verbose_name='CEP')),
                ('codigo_pais', models.IntegerField(blank=True, default=1058, null=True, verbose_name='Código do País')),
                ('nome_pais', models.CharField(blank=True, default='Brasil', max_length=20, null=True, verbose_name='País')),
                ('inscricao_estadual', models.IntegerField(blank=True, null=True, verbose_name='Inscrição Estadual')),
                ('fone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Fone')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='E-Mail')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.CharField(max_length=100)),
                ('editado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.CharField(max_length=100)),
                ('editado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('nome_razao_social', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(max_length=200, unique=True, verbose_name='Nome')),
                ('cpf', models.IntegerField(blank=True, null=True, unique=True, verbose_name='CPF')),
                ('cnpj', models.IntegerField(blank=True, null=True, unique=True, verbose_name='CNPJ')),
                ('inscricao_estadual', models.IntegerField(blank=True, null=True, verbose_name='Inscrição estadual')),
                ('rua_endereco', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rua')),
                ('numero_endereco', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('complemento_end', models.CharField(blank=True, max_length=200, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('cep', models.IntegerField(blank=True, null=True, verbose_name='CEP')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('pessoa_juridica', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Ibge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_estado', models.IntegerField(verbose_name='Código do Estado')),
                ('codigo_municipal', models.IntegerField(verbose_name='Código do Município')),
                ('pais', models.CharField(max_length=20, verbose_name='País')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.CharField(max_length=100)),
                ('editado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_de_barras', models.IntegerField(verbose_name='Código de Barras')),
                ('descricao', models.TextField(unique=True, verbose_name='Descrição do Produto')),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor da compra por unidade')),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor de venda por unidade')),
                ('ncm', models.IntegerField(verbose_name='NCM')),
                ('unidade', models.CharField(max_length=50, verbose_name='Unidade')),
                ('slug', models.SlugField(max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Categoria')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Tributacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(unique=True, verbose_name='Descrição')),
                ('csosn', models.IntegerField(verbose_name='CSOSN')),
                ('cfop_interno', models.IntegerField(verbose_name='CFOP Interno')),
                ('cfop_externo', models.IntegerField(verbose_name='CFOP Externo')),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='tributacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tributacao'),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='codigo_ibge_cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Ibge'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo_ibge_cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Ibge'),
        ),
    ]
