# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-29 02:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.CharField(max_length=100)),
                ('editado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('cidade', models.CharField(max_length=100)),
                ('fone', models.CharField(max_length=20)),
                ('cnpj_cpf', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('codigo_barras', models.IntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.CharField(max_length=100)),
                ('editado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('quantidade', models.CharField(max_length=100)),
                ('unidade_medida', models.CharField(blank=True, max_length=10, null=True)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=5)),
                ('slug', models.SlugField()),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Fornecedor')),
            ],
        ),
    ]
