# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-29 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='cidade',
            field=models.CharField(max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj_cpf',
            field=models.CharField(max_length=50, unique=True, verbose_name='CNPJ ou CPF'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='email',
            field=models.CharField(max_length=200, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='fone',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Raz\xe3o Social'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='unidade_medida',
            field=models.CharField(blank=True, choices=[('KG', 'KG'), ('L', 'L'), ('CX', 'CX')], max_length=10, null=True),
        ),
    ]
