# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-30 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180329_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo_barras',
            field=models.IntegerField(verbose_name='C\xf3digo de Barras'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='unidade_medida',
            field=models.CharField(blank=True, choices=[('UN', 'UN'), ('KG', 'KG'), ('L', 'L'), ('CX', 'CX')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valor_compra',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor da compra por unidade'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valor_venda',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor de venda por unidade'),
        ),
    ]
