# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180405_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(default='produto_default.png', upload_to='', verbose_name='Foto'),
        ),
    ]
