# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180405_0746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_venda', models.DateField(verbose_name='Data da venda')),
                ('valot_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Valor Total')),
                ('desconto_acrescimo', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Desconto ou Acréscimo')),
                ('forma_de_pagamento', models.CharField(choices=[(0, 'À Vista'), (1, 'Cartão'), (2, 'Fiado')], max_length=20, verbose_name='Forma de Pagamento')),
                ('numero_nfe', models.IntegerField(blank=True, null=True, verbose_name='Numero da Nota Fiscal Eletrónica')),
                ('serie_nfe', models.IntegerField(verbose_name='Série NFe')),
                ('protocolo_autorizacao_nfe', models.IntegerField(blank=True, null=True, verbose_name='Protocolo de Autorização')),
                ('chave_nfe', models.IntegerField(blank=True, null=True, verbose_name='Chave de Autorização')),
                ('status_nfe', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status da NFe')),
                ('observacao_venda', models.TextField(verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.CharField(max_length=100)),
                ('editado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente')),
            ],
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(default='produto_default.png', upload_to='', verbose_name='Imagem do Produto'),
        ),
    ]
