# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180330_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.CharField(max_length=100)),
                ('editado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=50, null=True)),
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('fone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('forma_de_pagamento', models.CharField(choices=[(0, '\xe0 vista'), (1, 'boleto'), (2, 'cheque'), (3, 'fiado')], max_length=20)),
            ],
        ),
    ]
