# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='forma_de_pagamento',
        ),
    ]
