# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180405_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='status_venda',
            field=models.CharField(choices=[(0, 'Pedido de compra'), (1, 'Vendido')], default=0, max_length=20, verbose_name='Status da Venda'),
        ),
    ]
