# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_cliente_forma_de_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cpf_cnpj',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
