# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_produto_status_venda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='status_venda',
        ),
        migrations.AddField(
            model_name='venda',
            name='status_venda',
            field=models.CharField(choices=[(0, 'Pedido'), (1, 'Vendido')], default=0, max_length=20, verbose_name='Status da Venda'),
        ),
    ]
