# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180405_1225'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Venda',
            new_name='CabecalhoNfe',
        ),
    ]
