# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cliente_cpf_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='slug',
            field=models.SlugField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
