# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180405_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabecalhonfe',
            name='observacao_venda',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
