# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180331_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(default='media/user.jpg', upload_to='media/'),
        ),
    ]
