# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180405_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabecalhonfe',
            name='forma_de_pagamento',
            field=models.IntegerField(choices=[(0, 'À Vista'), (1, 'Cartão'), (2, 'Fiado')], verbose_name='Forma de Pagamento'),
        ),
    ]
