# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180405_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItensNfe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.CharField(max_length=100)),
                ('quantidade_venda', models.IntegerField()),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Produto')),
            ],
        ),
    ]
