# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_itensnfe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabecalhonfe',
            name='numero_nfe',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Numero da Nota Fiscal Eletrónica'),
        ),
    ]
